FROM ubuntu

VOLUME /data
ENV TERM xterm

RUN apt-get update && \
    apt-get install -yq --no-install-recommends glusterfs-server && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

VOLUME /etc/glusterfs
COPY ./server.sh /tmp
RUN chmod ug+x /tmp/server.sh
CMD ["/tmp/server.sh"]
