FROM debian:stretch-slim

MAINTAINER Slavisa lukic  <lukic@gmx.ch>

ENV container docker

RUN apt-get update && \
    apt-get install -yq --no-install-recommends nfs-common glusterfs-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 
    
# Directory for coredumps. Note,kernel.core_pattern must be configured as such
RUN mkdir -p /var/log/core

CMD ["/bin/bash"]
