FROM debian:stretch-slim

VOLUME /data
ENV TERM xterm

RUN apt-get update && \
    apt-get install -yq --no-install-recommends glusterfs-server && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

CMD glusterd --no-daemon

