FROM debian:stretch-slim

RUN apt-get update && \
    apt-get install -yq --no-install-recommends glusterfs-server && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \    
    mkdir -p /etc/glusterfs_bkp /var/lib/glusterd_bkp /var/log/glusterfs_bkp && \
    cp -r /etc/glusterfs/* /etc/glusterfs_bkp && \
    cp -r /var/lib/glusterd/* /var/lib/glusterd_bkp 

COPY ./server.sh /tmp
RUN chmod ug+x /tmp/server.sh
CMD ["/tmp/server.sh"]
