FROM debian:stretch-slim

MAINTAINER Slavisa lukic  <lukic@gmx.ch>

ENV container docker
ENV LC_SRV=hostname
ENV GVOL=/gv0
ENV LC_DIR=/datavol

RUN apt-get update && \
    apt-get install -yq --no-install-recommends nfs-common glusterfs-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 
    
RUN mkdir -p /etc/glusterfs
COPY ./client.sh /etc/glusterfs
CMD ["/etc/glusterfs/client.sh"]
